Repository RoboJackets/igvc-software, pull requests merged in 2019-04, with the labels that each got.

#376 Add rplidar and velodyne lidar launch files and configuration
  igvc_gazebo/nodes/scan_to_pointcloud/main.cpp
  igvc_platform/launch/lidar.launch
  igvc_platform/launch/velodyne_lidar.launch
  igvc_platform/package.xml
  sandbox/igvc.rules
Labels: Hardware

#384 Update gazebo to incorporate recent scan_to_pointcloud changes and add ros_control build dependencies
  igvc_gazebo/launch/gazebo.launch
  igvc_gazebo/package.xml
Labels: simulation

#372 Parameter assertions
  igvc_navigation/src/field_d_planner/FieldDPlanner.cpp
  igvc_navigation/src/path_follower/path_follower.cpp
  igvc_utils/CMakeLists.txt
  igvc_utils/include/igvc_utils/NodeUtils.hpp
  igvc_utils/package.xml
  igvc_utils/src/tests/CMakeLists.txt
  igvc_utils/src/tests/test/test_assertions.test
  igvc_utils/src/tests/test_assertions.cpp
Labels: enhancement

#404 Hotfix/joystick test bug
  igvc_platform/src/tests/test_joystick_driver.cpp
Labels: IMPORTANT, bug

#412 Refactor perception and sim_detector nodes to make use of all cameras
  igvc_description/urdf/jessii.urdf.xacro
  igvc_gazebo/launch/qualification.launch
  igvc_gazebo/launch/sim_detector.launch
  igvc_gazebo/nodes/sim_color_detector/main.cpp
  igvc_navigation/launch/octomap.yaml
  igvc_navigation/launch/octomap_sim.yaml
  igvc_perception/launch/vision.launch
  igvc_perception/src/cnn/cnn.py
  igvc_rviz_plugins/configs/jessii_conf.rviz
Labels: computer vision, gazebo

#399 Camera lidar projection
  .gitignore
  igvc_gazebo/launch/qualification.launch
  igvc_perception/CMakeLists.txt
  igvc_perception/launch/projection.launch
  igvc_perception/src/projection/CMakeLists.txt
  igvc_perception/src/projection/main.cpp
  igvc_rviz_plugins/configs/jessii_conf.rviz
Labels: computer vision

#396 Three cameras for octomapper
  igvc_navigation/launch/octomap.yaml
  igvc_navigation/src/mapper/map_utils.cpp
  igvc_navigation/src/mapper/mapper.cpp
  igvc_navigation/src/mapper/mapper.h
  igvc_navigation/src/mapper/octomapper.cpp
  igvc_navigation/src/mapper/ros_mapper.cpp
  igvc_navigation/src/mapper/ros_mapper.h
Labels: enhancement
