Repository RoboJackets/igvc-software, pull requests merged in 2019-10, with the labels that each got.

#517 Changed ensure_submodules to check for .git folder inside submodule
  cmake/ensure_submodules.cmake
Labels: type ➤ bug

#514 `lidar_layer` part of the mapper refactor
  igvc_navigation/CMakeLists.txt
  igvc_navigation/config/empty_global_costmap_params.yaml
  igvc_navigation/config/gridmap_viz.yaml
  igvc_navigation/config/refactored_local_costmap_params.yaml
  igvc_navigation/include/mapper/probability_utils.h
  igvc_navigation/launch/gridmap_viz.launch
  igvc_navigation/launch/refactored_mapper.launch
  igvc_navigation/package.xml
  igvc_navigation/src/mapper/CMakeLists.txt
  igvc_navigation/src/mapper/costmap_plugins.xml
  igvc_navigation/src/mapper/eigen_hash.h
  igvc_navigation/src/mapper/lidar_config.cpp
  igvc_navigation/src/mapper/lidar_config.h
  igvc_navigation/src/mapper/lidar_layer.cpp
  igvc_navigation/src/mapper/lidar_layer.h
  igvc_navigation/src/mapper/lidar_layer_config.cpp
  igvc_navigation/src/mapper/lidar_layer_config.h
  igvc_navigation/src/mapper/map_config.cpp
  igvc_navigation/src/mapper/map_config.h
  igvc_perception/config/pointcloud_filter.yaml
  igvc_perception/include/pointcloud_filter/raycast_filter/raycast_filter.h
  igvc_perception/include/pointcloud_filter/raycast_filter/raycast_filter_config.h
  igvc_perception/src/pointcloud_filter/pointcloud_filter.cpp
  igvc_perception/src/pointcloud_filter/raycast_filter/raycast_filter.cpp
  igvc_perception/src/pointcloud_filter/raycast_filter/raycast_filter_config.cpp
Labels: area ➤ mapping, type ➤ refactor

#515 Changes camera frame + topics to use namespaces more, clean up segmented image and camera_info topic, adds camera intrinsics matrix scaling and publishing for sim_detector
  igvc_description/urdf/jessii.urdf.xacro
  igvc_gazebo/launch/sim_detector.launch
  igvc_gazebo/nodes/sim_color_detector/main.cpp
  igvc_navigation/config/octomap.yaml
  igvc_navigation/config/octomap_sim.yaml
  igvc_platform/launch/camera.launch
Labels: area ➤ gazebo, area ➤ mapping, type ➤ misc, type ➤ refactor

#524 Feat/line layer
  igvc_description/urdf/gazebo.material
  igvc_description/urdf/textures/qualification_course.png
  igvc_gazebo/launch/qualification.launch
  igvc_gazebo/launch/sim_detector.launch
  igvc_gazebo/nodes/sim_color_detector/main.cpp
  igvc_navigation/CMakeLists.txt
  igvc_navigation/config/gridmap_viz.yaml
  igvc_navigation/config/refactored_local_costmap_params.yaml
  igvc_navigation/launch/refactored_mapper.launch
  igvc_navigation/src/mapper/CMakeLists.txt
  igvc_navigation/src/mapper/camera_config.cpp
  igvc_navigation/src/mapper/camera_config.h
  igvc_navigation/src/mapper/costmap_plugins.xml
  igvc_navigation/src/mapper/lidar_layer_config.h
  igvc_navigation/src/mapper/line_layer.cpp
  igvc_navigation/src/mapper/line_layer.h
  igvc_navigation/src/mapper/line_layer_config.cpp
  igvc_navigation/src/mapper/line_layer_config.h
  igvc_navigation/src/mapper/map_config.cpp
  igvc_navigation/src/mapper/map_config.h
  igvc_navigation/src/mapper/projection_config.cpp
  igvc_navigation/src/mapper/projection_config.h
  igvc_perception/CMakeLists.txt
  igvc_perception/config/pointcloud_filter.yaml
  igvc_perception/src/pointcloud_filter/tf_transform_filter/tf_transform_filter.cpp
Labels: area ➤ mapping, type ➤ new feature, type ➤ refactor

#530 fixed compressed_to_raw bag file to take in topic name arg
  igvc_perception/launch/compressed_to_raw.launch
  igvc_utils/launch/compressed_to_raw.launch
Labels: type ➤ bug

#528 Force color if ninja generator is used
  igvc.cmake
Labels: type ➤ misc

#529 Fix gazebo 90 degree offset
  igvc_description/urdf/jessii.urdf.xacro
  igvc_gazebo/launch/qualification.launch
  igvc_gazebo/nodes/ground_truth/main.cpp
  igvc_navigation/launch/localization.launch
  igvc_utils/src/quaternion_to_rpy/main.cpp
Labels: area ➤ gazebo, area ➤ localization, type ➤ bug

#535 Final mapper + TEB integration as part of MBF refactor
  igvc_navigation/config/empty_global_costmap_params.yaml
  igvc_navigation/config/global_costmap_params.yaml
  igvc_navigation/config/local_costmap_params.yaml
  igvc_navigation/config/refactored_local_costmap_params.yaml
  igvc_navigation/config/teb_local_planner_params.yaml
  igvc_navigation/launch/mbf_navigation.launch
  igvc_navigation/launch/navigation_simulation.launch
  igvc_navigation/launch/navigation_simulation_teb.launch
  igvc_navigation/launch/refactored_mapper.launch
  igvc_navigation/src/mapper/CMakeLists.txt
  igvc_navigation/src/mapper/lidar_layer.cpp
  igvc_navigation/src/mapper/line_layer.cpp
  igvc_navigation/src/mapper/line_layer.h
  igvc_navigation/src/mapper/map_config.cpp
  igvc_navigation/src/mapper/map_config.h
  igvc_navigation/src/mapper/wrapper_layer.cpp
  igvc_navigation/src/mapper/wrapper_layer.h
Labels: area ➤ gazebo, area ➤ mapping, area ➤ path planning, type ➤ new feature, type ➤ refactor

#533 Only update cells if they were updated, ie. "dirty"
  igvc_navigation/config/local_costmap_params.yaml
  igvc_navigation/src/mapper/CMakeLists.txt
  igvc_navigation/src/mapper/gridmap_layer.cpp
  igvc_navigation/src/mapper/gridmap_layer.h
  igvc_navigation/src/mapper/lidar_layer.cpp
  igvc_navigation/src/mapper/lidar_layer.h
  igvc_navigation/src/mapper/line_layer.cpp
  igvc_navigation/src/mapper/line_layer.h
  igvc_navigation/src/mapper/map_config.cpp
  igvc_navigation/src/mapper/map_config.h
Labels: area ➤ mapping, type ➤ new feature, type ➤ refactor

#531 Fixes mesh resolving problems in rviz
  igvc_description/launch/robot_state_publisher.launch
  igvc_description/urdf/jessii.urdf.xacro
  igvc_platform/launch/sensors.launch
Labels: type ➤ misc

#525 Created new barrel that doesn't have wide base
  igvc_description/urdf/models/barrel/meshes/Barrel.png
  igvc_description/urdf/models/barrel/meshes/barrel.dae
  igvc_description/urdf/models/barrel/model.config
  igvc_description/urdf/models/barrel/model.sdf
  igvc_description/urdf/worlds/qualification.world
Labels: area ➤ gazebo, type ➤ refactor

#545 Clang-tidy on codebase
  .circleci/config.yml
  .circleci/utils/clang-tidy-to-junit.py
  .circleci/utils/tidy.sh
  .clang-tidy
  Makefile
  igvc_demo/scripts/.idea/workspace.xml
  igvc_navigation/src/mapper/eigen_hash.h
  igvc_navigation/src/mapper/gridmap_layer.cpp
  igvc_navigation/src/mapper/gridmap_layer.h
  igvc_navigation/src/mapper/lidar_layer.cpp
  igvc_navigation/src/mapper/line_layer.cpp
  igvc_navigation/src/mapper/line_layer.h
Labels: type ➤ misc, type ➤ style

#559 Added check for if no cpp files were modified
  .circleci/utils/tidy.sh
Labels: area ➤ CI, type ➤ bug

#561 Created ramp model and added to qualifications worlds
  igvc_description/urdf/models/ramp/meshes/RampTexture.png
  igvc_description/urdf/models/ramp/meshes/ramp.dae
  igvc_description/urdf/models/ramp/model.config
  igvc_description/urdf/models/ramp/model.sdf
  igvc_description/urdf/worlds/qualification.world
Labels: area ➤ gazebo, type ➤ new feature
