Repository RoboJackets/igvc-software, pull requests merged in 2019-11, with the labels that each got.

#578 Fixed nondeterministic bug in joystick test by creating helper class
  igvc_platform/src/tests/test_joystick_driver.cpp
Labels: area ➤ CI, type ➤ bug

#553 Created "standard" rviz config and launch file
  igvc_rviz_plugins/CMakeLists.txt
  igvc_rviz_plugins/configs/jessii_conf.rviz
  igvc_rviz_plugins/launch/rviz.launch
Labels: type ➤ misc

#579 Created correct footprint based on CAD measurements
  igvc_navigation/config/global_costmap_params.yaml
  igvc_navigation/config/local_costmap_params.yaml
Labels: area ➤ mapping, area ➤ path planning, type ➤ bug

#587 Updated readme with picture of jessii
  readme.md
Labels: github

#591 Add max distance for line_layer
  igvc_navigation/config/global_costmap_params.yaml
  igvc_navigation/config/local_costmap_params.yaml
  igvc_navigation/src/mapper/camera_config.cpp
  igvc_navigation/src/mapper/camera_config.h
  igvc_navigation/src/mapper/line_layer.cpp
Labels: area ➤ mapping, level ➤ easy, type ➤ new feature

#595 New member projects design document template
  documents/design/new_member_project.md
Labels: type ➤ design document

#585 Ignore generated files
  .circleci/utils/tidy.sh
Labels: area ➤ CI, type ➤ bug

#609 Update clang-format
  .clang-format
Labels: type ➤ bug

#594 Add software lead icon to readme
  readme.md
Labels: github, type ➤ misc

#613 Merged waypoint_source and action_server into navigation_client
  igvc_gazebo/launch/simulation.launch
  igvc_navigation/CMakeLists.txt
  igvc_navigation/launch/action_server.launch
  igvc_navigation/launch/navigation_client.launch
  igvc_navigation/launch/navigation_simulation.launch
  igvc_navigation/launch/waypoint_source.launch
  igvc_navigation/src/action_server/CMakeLists.txt
  igvc_navigation/src/action_server/action_server.cpp
  igvc_navigation/src/action_server/action_server.h
  igvc_navigation/src/navigation_client/CMakeLists.txt
  igvc_navigation/src/navigation_client/navigation_client.cpp
  igvc_navigation/src/navigation_client/navigation_client.h
  igvc_navigation/src/waypoint_source/CMakeLists.txt
  igvc_navigation/src/waypoint_source/waypoint_source.cpp
  igvc_navigation/src/waypoint_source/waypoint_source.h
Labels: New members 👍🏻, area ➤ path planning, type ➤ new feature
