Repository RoboJackets/igvc-software, pull requests merged in 2019-09, with the labels that each got.

#481 Created PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: github

#488 Created costmap2d layer thin wrapper around current mapper
  igvc_navigation/CMakeLists.txt
  igvc_navigation/config/controllers.yaml
  igvc_navigation/config/global_costmap_params.yaml
  igvc_navigation/config/local_costmap_params.yaml
  igvc_navigation/config/octomap.yaml
  igvc_navigation/config/octomap_sim.yaml
  igvc_navigation/config/planners.yaml
  igvc_navigation/config/recovery_behaviors.yaml
  igvc_navigation/launch/mapper.launch
  igvc_navigation/launch/mapper_sim.launch
  igvc_navigation/launch/mapper_wrapper.launch
  igvc_navigation/launch/navigation_simulation.launch
  igvc_navigation/package.xml
  igvc_navigation/src/mapper/CMakeLists.txt
  igvc_navigation/src/mapper/costmap_plugins.xml
  igvc_navigation/src/mapper/mapper_node.cpp
  igvc_navigation/src/mapper/ros_mapper.cpp
  igvc_navigation/src/mapper/ros_mapper.h
  igvc_navigation/src/mapper/wrapper_layer.cpp
  igvc_navigation/src/mapper/wrapper_layer.h
Labels: area ➤ mapping, type ➤ refactor

#491 cmake git submodule check, added common problems to readme
  cmake/ensure_submodules.cmake
  igvc.cmake
  readme.md
Labels: github, type ➤ structural

#495 Feat/implement costmap2d interfaces
  igvc_navigation/config/global_costmap_params.yaml
  igvc_navigation/config/local_costmap_params.yaml
  igvc_navigation/launch/mapper_wrapper.launch
  igvc_navigation/src/mapper/ros_mapper.h
  igvc_navigation/src/mapper/wrapper_layer.cpp
  igvc_navigation/src/mapper/wrapper_layer.h
Labels: area ➤ mapping, type ➤ refactor

#499 Reduce CPU usage by sim_color_detector
  igvc_gazebo/nodes/sim_color_detector/main.cpp
Labels: area ➤ computer vision, area ➤ gazebo, type ➤ bug

#494 Fix trajectory planner crashing when trajectory is empty
  igvc_navigation/src/trajectory_planner/trajectory_planner.cpp
  igvc_navigation/src/trajectory_planner/trajectory_planner.h
Labels: area ➤ path planning, type ➤ bug

#500 Bug/trajectory planner runs as fast as possible
  igvc_navigation/src/trajectory_planner/trajectory_planner.cpp
Labels: area ➤ path planning, type ➤ bug

#509 Pointcloud filter node
  igvc_navigation/CMakeLists.txt
  igvc_perception/CMakeLists.txt
  igvc_perception/config/pointcloud_filter.yaml
  igvc_perception/include/pointcloud_filter/back_filter/back_filter.h
  igvc_perception/include/pointcloud_filter/back_filter/back_filter_config.h
  igvc_perception/include/pointcloud_filter/bundle.h
  igvc_perception/include/pointcloud_filter/filter.h
  igvc_perception/include/pointcloud_filter/ground_filter/ground_filter.h
  igvc_perception/include/pointcloud_filter/ground_filter/ground_filter_config.h
  igvc_perception/include/pointcloud_filter/pointcloud_filter.h
  igvc_perception/include/pointcloud_filter/pointcloud_filter_config.h
  igvc_perception/include/pointcloud_filter/radius_filter/radius_filter.h
  igvc_perception/include/pointcloud_filter/radius_filter/radius_filter_config.h
  igvc_perception/include/pointcloud_filter/raycast_filter/raycast_filter.h
  igvc_perception/include/pointcloud_filter/raycast_filter/raycast_filter_config.h
  igvc_perception/include/pointcloud_filter/tf_transform_filter/tf_transform_filter.h
  igvc_perception/launch/pointcloud_filter.launch
  igvc_perception/src/pointcloud_filter/CMakeLists.txt
  igvc_perception/src/pointcloud_filter/back_filter/back_filter.cpp
  igvc_perception/src/pointcloud_filter/back_filter/back_filter_config.cpp
  igvc_perception/src/pointcloud_filter/bundle.cpp
  igvc_perception/src/pointcloud_filter/ground_filter/ground_filter.cpp
  igvc_perception/src/pointcloud_filter/ground_filter/ground_filter_config.cpp
  igvc_perception/src/pointcloud_filter/pointcloud_filter.cpp
  igvc_perception/src/pointcloud_filter/pointcloud_filter_config.cpp
  igvc_perception/src/pointcloud_filter/pointcloud_filter_node.cpp
  igvc_perception/src/pointcloud_filter/radius_filter/radius_filter.cpp
  igvc_perception/src/pointcloud_filter/radius_filter/radius_filter_config.cpp
  igvc_perception/src/pointcloud_filter/raycast_filter/raycast_filter.cpp
  igvc_perception/src/pointcloud_filter/raycast_filter/raycast_filter_config.cpp
  igvc_perception/src/pointcloud_filter/tf_transform_filter/tf_transform_filter.cpp
Labels: area ➤ mapping, type ➤ new feature
