Repository RoboJackets/igvc-software, pull requests merged in 2020-03, with the labels that each got.

#422 rviz IMU plugin
  igvc_rviz_plugins/CMakeLists.txt
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/bat_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/eStop_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/example_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/launch_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/my_thread.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/node_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/num_button.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/sensor_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/speed_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/speedometer.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/time_panel.h
  igvc_rviz_plugins/include/igvc_rviz_plugins_old/waypoint_panel.h
  igvc_rviz_plugins/include/imu_viz/imu_display.h
  igvc_rviz_plugins/include/imu_viz/imu_visual.h
  igvc_rviz_plugins/plugin_description.xml
  igvc_rviz_plugins/src/igvc_rviz_plugins/CMakeLists.txt
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/CMakeLists.txt
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/bat_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/eStop_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/example_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/launch_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/my_thread.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/node_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/num_button.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/sensor_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/speed_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/speedometer.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/time_panel.cpp
  igvc_rviz_plugins/src/igvc_rviz_plugins_old/waypoint_panel.cpp
  igvc_rviz_plugins/src/imu_viz/CMakeLists.txt
  igvc_rviz_plugins/src/imu_viz/imu_display.cpp
  igvc_rviz_plugins/src/imu_viz/imu_visual.cpp
Labels: area ➤ rviz plugin, level ➤ easy, type ➤ new feature

#676 Removed duplicate key names in yaml
  .circleci/config.yml
  igvc_navigation/CMakeLists.txt
Labels: area ➤ CI

#683 Lowered resolution to same as hardware cameras
  igvc_description/urdf/jessii.urdf.xacro
Labels: area ➤ gazebo

#642 Added design document for slope detection.
  documents/design/slope_detection.md
Labels: area ➤ mapping, area ➤ path planning
