Repository RoboJackets/igvc-software, pull requests merged in 2020-02, with the labels that each got.

#648 Bug/rviz nav goal cancel
  igvc_navigation/src/navigation_server/navigation_server.cpp
  igvc_navigation/src/navigation_server/navigation_server.h
Labels: area ➤ path planning, type ➤ bug

#650 Updated port to 5333 (IGVC)
  igvc_platform/launch/motor_controller.launch
Labels: area ➤ firmware

#641 Created CNN model visualizer node
  .gitignore
  .pep8speaks.yaml
  igvc_perception/launch/nn_viz.launch
  igvc_perception/src/nn_viz/__init__.py
  igvc_perception/src/nn_viz/models/__init__.py
  igvc_perception/src/nn_viz/models/unet.py
  igvc_perception/src/nn_viz/nn_viz.py
  igvc_perception/src/nn_viz/visualizer.py
Labels: area ➤ neural network, type ➤ new feature

#640 Fix bug in TEB config + lower speeds for safety reasons
  igvc_navigation/config/teb_local_planner_params.yaml
  igvc_navigation/launch/differential_drive.launch
Labels: area ➤ path planning, area ➤ trajectory following, type ➤ bug
